version: '3'

services:
  api:
    container_name: short-api
    build: 
      context: .
      dockerfile: ./docker/api/Dockerfile
    privileged: true
    ports:
      - "5900:5900"
    volumes:
      # Binds volume for local Google Account Credentials
      - ~/.config/gcloud:/root/.config/gcloud
      # Binds volume for local ML models
      - ./models:/app/models
    env_file:
      - .env
    environment:
      - SKIPTHOUGHTS_MODELS_PATH=/app/models/
      - SKIPTHOUGHTS_TABLES_PATH=/app/models/
      - GCS_BUCKET=${MODEL_BUCKET}
    restart: always
    