version: '3'
services:
  app:
    container_name: breef_app
    build: .
    ports:
      - "5900:5900"
    volumes:
      # Binds volume for Google Account Credentials
      - ~/.config:/root/.config 
      # Binds volume for ML models
      - ./models:/app/models