#!/usr/bin/env python
# -*- coding: utf-8 -*

from dotenv import load_dotenv
load_dotenv()

from summarization import summarize
import sys

reload(sys)
sys.setdefaultencoding('utf8')

summaries = summarize([
  "Judgments of beauty are based on feeling, in particular feelings of pleasure (Kant also mentions displeasure, but this does not figure prominently in his account; for more on this point, see Section 2.3.6 below). The pleasure, however, is of a distinctive kind: it is disinterested, which means that it does not depend on the subject's having a desire for the object, nor does it generate such a desire. The fact that judgments of beauty are based on feeling rather than \"objective sensation\" (e.g., the sensation of a thing's colour) distinguishes them from cognitive judgments based on perception (e.g., the judgment that a thing is green). But the disinterested character of the feeling distinguishes them from other judgments based on feeling. In particular, it distinguishes them from (i) judgments of the agreeable, which are the kind of judgment expressed by saying simply that one likes something or finds it pleasing (for example, food or drink), and (ii) judgments of the good, including judgments both about the moral goodness of something and about its goodness for particular non-moral purposes.", 
  "Judgments of beauty have, or make a claim to, \"universality\" or \"universal validity.\" (Kant also uses the expression \"universal communicability\"; this can be taken as equivalent to \"universal validity.\") That is, in making a judgment of beauty about an object, one takes it that everyone else who perceives the object ought also to judge it to be beautiful, and, relatedly, to share one's pleasure in it. But the universality is not \"based on concepts.\" That is, one's claim to agreement does not rest on the subsumption of the object under a concept (in the way, for example, that the claim to agreement made by the judgment that something is green rests on the ascription to the object of the property of being green, and hence its subsumption under the concept green). It follows from this that judgments of beauty cannot, despite their universal validity, be proved: there are no rules by which someone can be compelled to judge that something is beautiful (Kant expands on this point in 32–33). More strongly, judgments of beauty are not to be understood as predicating the concept beauty of their objects: as he puts it later, \"beauty is not a concept of the object\" (38, 290). Still later, in the \"Antinomy of Taste,\" Kant seems to go back on this strong claim by saying that a judgment of beauty rests on an \"indeterminate concept\" (57, 341); however, by \"concept\" here he diverges from the standard use of the term \"concept\" as referring to a kind of representation which can figure in cognition.", 
  "Unlike judgments of the good, judgments of the beautiful do not presuppose an end or purpose [Zweck] which the object is taken to satisfy. (This is closely related to the point that their universality is not based on concepts). However, they nonetheless involve the representation of what Kant calls \"purposiveness\" [Zweckmässigkeit]. Because this representation of purposiveness does not involve the ascription of an purpose, Kant calls the purposiveness which is represented \"merely formal purposiveness\" or \"the form of purposiveness.\" He describes it as perceived both in the object itself and in the activity of imagination and understanding in their engagement with the object. (For more on this activity, see the discussion of the \"free play of the faculties\" in Section 2.2; for more on the notion of purposiveness, see Section 3.1.) The Third Moment, in particular 14, is the main evidence for Kant's supposed formalism in aesthetics; for more on Kant's formalism, see Section 2.4."
])
print summaries