apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: api-deployment
  spec:
    selector:
      matchLabels:
        io.kompose.service: api
    replicas: 1
    template:
      metadata:
        labels:
          io.kompose.service: api
      spec:
        containers:
        - name: short-api
          image: gcr.io/breef-247014/breef_api
          ports:
          - containerPort: 5900
          env:
          - name: GCS_BUCKET
            value: breef-models
          - name: SKIPTHOUGHTS_MODELS_PATH
            value: /mnt/disk/models/
          - name: SKIPTHOUGHTS_TABLES_PATH
            value: /mnt/disk/models/
          volumeMounts:
          - mountPath: "/mnt/disk"
            name: short-disk
          resources: 
            requests:
              memory: "8096Mi"
              cpu: "500m"
            limits:
              memory: "16384Mi"
              cpu: "1000m"
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5900
        volumes:
        - name: short-disk
          persistentVolumeClaim:
            claimName: short-disk
        restartPolicy: Always
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: api
    labels:
      io.kompose.service: api
  spec:
    type: NodePort
    selector:
      io.kompose.service: api
    ports:
    - name: "5900"
      port: 5900
      targetPort: 5900